### ISSUE TITLE
Problem with mod inside block

### ISSUE THREAD

**Issue by Yeti-or** [bem/bem-react-core#61]
```
// block.js

import 'm:mod';
// require('block_mod.js').applyDecl();

export default decl({
  block: 'name',
  content: 'hello '
});
```

```
// block_mod.js

export default declMod({
  block: 'name',
  content() {
    return this.__base(...arguments) + 'world';
  }
})
```

Here we enter in block.js,
then require block_mod.js and apply it's decl.
but at this moment block's `decl` wasn't  executed, so `./lib/decls.js` fails here:
https://github.com/bem/bem-react-core/blob/master/lib/decls.js#L47

**Comment by awinogradov** [comment]
🙀

**Comment by awinogradov** [comment]
```
TypeError: Cannot read property 'prototype' of null

      at Object.applyEntityDecls [as applyDecls] (lib/decls.js:48:32)
      at Object.<anonymous> (__tests__/fixtures1.blocks/BlockWithRequiredMod/BlockWithRequiredMod.js:3:132)
      at Object.<anonymous> (__tests__/orderOfMod.spec.js:3:57)
      at process._tickCallback (internal/process/next_tick.js:103:7)
```
