### ISSUE TITLE
Can't resolve decl in required self mod

### ISSUE THREAD

**Issue by awinogradov** [bem/bem-react-core#66]
```
TypeError: Cannot read property 'prototype' of null

      at Object.applyEntityDecls [as applyDecls] (lib/decls.js:48:32)
      at Object.<anonymous> (__tests__/fixtures1.blocks/BlockWithRequiredMod/BlockWithRequiredMod.js:3:132)
      at Object.<anonymous> (__tests__/orderOfMod.spec.js:3:57)
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by awinogradov** [comment]
Relates to #61
